// SustentArte/src/app/shared/footer/footer.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {
}

<div class="contenedor" style="height: auto; width: 100%;">
  <div class="container-fluid mt-0">
      <div class="row">
          <div
              class="col-5" style="margin-left: 20px;"
          >
              <h4>SUSTENTARTE</h4>
              <h5>"Vive una vida sustentable"</h5>
          </div>
          <div
              class="col"
          >

          </div>
          <div
              class="col-4"
          >
              <div class="container-fluid">
                  <div class="row mt-4 mr">
                  <div
                          class="col-6 textoContact "
                      >
                          <h5 style="text-align: center; margin-right: 10px;" class="textoContact">Contactanos en:</h5>
                      </div>
                      <div class="col-1">

                      </div>
                      <div
                          class="col-1"
                      >
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                      </div>
                      <div
                          class="col-1"
                      >
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                      </div>
                      <div
                          class="col-1"
                      >
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

// front/src/components/footer/footer.jsx
import React from 'react'
import styles from "./footer.module.css";
import { FaFacebook , FaInstagram, FaTwitter} from 'react-icons/fa';

export const footer = () => {
  return (
    <>
        <div className={styles.contenedor}>
            <div className="container-fluid m-2 mb-1 ml-2 mr-1">
                <div className="row">
                    <div
                        className="col-4"
                    >
                        <h4>SUSTENTARTE</h4>
                        <h5>"Vive una vida sustentable"</h5>
                    </div>
                    <div
                        className="col-2"
                    >
                        
                    </div>
                    <div
                        className="col-6"
                    >
                        <div className="container-fluid">
                            <div className="row mt-4 mr">
                            <div
                                    className="col-6 mt-2"
                                >
                                    <h5 style={{ textAlign: 'right' }}>Contactanos en:</h5>
                                </div>
                                <div
                                    className="col-1"
                                >
                                    <a href=""><h2><FaFacebook/></h2></a>
                                </div>
                                <div
                                    className="col-1"
                                >
                                    <a href=""><h2><FaInstagram/></h2></a>
                                </div>
                                <div
                                    className="col-1"
                                >
                                    <a href=""><h2><FaTwitter/></h2></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </>
  )
}

export default footer;
