// front/src/components/navbar/navbar.jsx
import React from "react";
import styles from "./navbar.module.css";
import Image from "next/image";

const Navbar = () => {
  return (
    <div>
      <nav className="navbar navbar-expand-lg navbar-white bg-white">
        <div className="container">
          <Image src="/Logo.jpeg" alt="ImagenCarrousell" width={110} height={80} />
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="collapsibleNavId">
            <ul className="navbar-nav ms-auto flex-lg-row flex-column navItems">
              <li className="nav-item">
                <a
                  className="nav-link active"
                  href="/"
                  aria-current="page"
                >
                  Inicio
                  <span className="visually-hidden">(current)</span>
                </a>
              </li>
              <li className="nav-item">
                <a
                  className="nav-link active"
                  href="/Nosotros"
                  aria-current="page"
                >
                  ¿Quienes Somos?
                  <span className="visually-hidden">(current)</span>
                </a>
              </li>
              <li className="nav-item">
                <a
                  className="nav-link active"
                  href="#"
                  aria-current="page"
                >
                  Productos
                  <span className="visually-hidden">(current)</span>
                </a>
              </li>
              <li className="nav-item">
                <button
                    type="button"
                    className={styles.logout}
                >
                    Iniciar Sesion
                </button>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossOrigin="anonymous"
      ></script>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossOrigin="anonymous"
      ></script> 
    </div>
  );
};

export default Navbar;

// SustentArte/src/app/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  rol: string = '';

  constructor() {
    this.rol = sessionStorage.getItem('rol') || '';
  }
  clearSessionStorage() {
    sessionStorage.clear();
  }
}

<div class="container-fluid">
  <nav class="navbar navbar-expand-sm navbar-white bg-white">
    <div class="container">
      <a class="navbar-brand" href="#"><img src="assets/img/Logo.jpeg" class="logo" alt="LOGO"></a>
      <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse"
        data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item elementos">
            <a class="nav-link active" routerLinkActive="active" routerLink="../home" aria-current="page">Inicio<span
                class="visually-hidden">(current)</span></a>
          </li>
          <li class="nav-item elementos">
            <a class="nav-link active" routerLinkActive="active" routerLink="../nosotros" aria-current="page">Nosotros<span
                class="visually-hidden">(current)</span></a>
          </li>
          <li class="nav-item elementos">
            <a class="nav-link active" routerLinkActive="active" routerLink="../vendedores" aria-current="page">Artesanos<span class="visually-hidden">(current)</span></a>
          </li>
          @if(rol=='administador') {
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="panelAdmin"
                aria-current="page">Panel Administrador<span class="visually-hidden">(current)</span></a>
            </li>
          }
          @if(rol=='atesano') {
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="panelVendedor"
                aria-current="page">Panel Artesano<span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="misProductosVendedor"
                aria-current="page">Mis Productos <i class="fa-solid fa-store"></i> <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="ventasVendedor"
                aria-current="page">Mis Ventas <i class="fa-solid fa-truck-fast"></i><span class="visually-hidden">(current)</span></a>
            </li>
          }
          @if(rol=='comprador') {
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="productoPrivate"
                aria-current="page">Productos<span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="productosComprados"
                aria-current="page">Compras</a>
            </li>
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="carritoComprador"
                aria-current="page">Mi Carrito<i class="fa fa-shopping-cart" aria-hidden="true"></i><span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="perfilComprador"
                aria-current="page">Perfil</a>
            </li>
          }
          @if (rol=='') {
            <li class="nav-item elementos">
              <a class="nav-link active" routerLinkActive="active" routerLink="../productos"
                aria-current="page">Productos<span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" routerLinkActive="active" routerLink="../login" aria-current="page">
                <button type="button" class="btn bgColor">Login</button>
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" routerLinkActive="active" routerLink="../register" aria-current="page">
                <button type="button" class="btn bgColor">Register</button>
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
          }
          @if(rol=='administador' || rol=='comprador' || rol=='atesano') {
            <li class="nav-item">
              <a class="nav-link active" routerLinkActive="active" routerLink="../home" aria-current="page">
                <button type="button" class="btn bgColor closeSession" (click)="clearSessionStorage()">
                  Cerrar Sesion
                </button>
                <span class="visually-hidden">(current)</span>
              </a>
            </li>
          }
          
          
        </ul>
      </div>
    </div>
  </nav>
</div>
